### ISSUE TITLE
Setting `PLAYDATE_SERIAL_DEVICE` forces `--device` flag

### ISSUE THREAD

**Issue by paulyoung** [boozook/playdate#279] opened 2024-04-06 23:41 UTC
I'm using a Nix dev shell where `PLAYDATE_SERIAL_DEVICE` is always set for convenience.

If I do `cargo playdate run` I see `Running hello-world on the '/dev/cu.usbmodemXXXX_XXXXXXX'`, but if I do `cargo playdate run --simulator` I get `error: the argument '--simulator' cannot be used with '--device [<device>]'`

The only way to prevent this behavior is to go into my dev shell config and comment out `PLAYDATE_SERIAL_DEVICE`.

**Comment by boozook** [comment] 2024-04-09 14:51
Thanks, @paulyoung.
But I'm not sure what's wrong. The arg `--device` have optional value to point what device you want to use, That value have fallback as env var `PLAYDATE_SERIAL_DEVICE`. So if I see you've set `PLAYDATE_SERIAL_DEVICE` - that means you're set value for `--device` parameter.

Error causes because command `run` can consume only one target - `sim` or `dev`. So, for example, if you do `package` command, there should be produced package with bins for device __and__ your host simulator.

__Probably__ I shouldn't read env if no `--device` arg passed? I can understand it, it's reasoned. But it's logic of clap, I suppose. I'll take a look at it, thanks 👍.

Could you try some [latest beta builds of cargo-playdate](https://github.com/boozook/playdate/releases/tag/2024.04.02)?

**Comment by boozook** [comment] 2024-04-09 18:10
I think nothing wrong. Setting `PLAYDATE_SERIAL_DEVICE` you're setting value for `--device` parameter, so this is expected behaviour. Please correct me if I'm missing something.

**Comment by boozook** [comment] 2024-04-09 18:30
But proooobably I can create special priority for this case. Something like this: "is `--device` have value __from ENV__, if actually `--device` isn't presented in args (real args, but not clap's) __and__ `--simulator` arg is here => so simulator target should be chosen". But I'm really not sure is this really needed.

**Comment by paulyoung** [comment] 2024-04-12 02:13
If the beta version is on the main branch then I think I was using that already. It's the commit I mentioned in https://github.com/boozook/playdate/issues/278#issuecomment-2050839401

The special case you mentioned seems necessary and makes sense, unless I'm not using a beta version. I can check at the weekend.

Withe the behavior I experienced it makes changing between simulator and device really cumbersome.

**Comment by boozook** [comment] 2024-04-12 07:27
Ok, I've re-viewed all of this and now understood that you're right. Sorry for this mistake, this is a bug definitely.

Well, this is bug because value of `--device[=SN-or-PORT]` is optional, the env var have to be fallback for the value, but not set `--device` argument. But currently it implicitly set `--device` with value.

Thanks for the issue 👍

**Comment by boozook** [comment] 2024-04-12 07:36
Fixed in #290. Thanks, @paulyoung 👍

**Closed by boozook** 2024-04-12 07:36 UTC
Labels: bug, cargo

**Comment by paulyoung** [comment] 2024-04-18 00:16
Thanks @boozook!
