### ISSUE TITLE
`run` command with `--device` flag gets stuck

### ISSUE THREAD

**Issue by paulyoung** [boozook/playdate#326] opened 2024-04-25 03:46 UTC
As discussed in https://github.com/boozook/playdate/issues/314#issuecomment-2065686756

When I attempt to use `cargo playdate run --device` I can't get past the device showing "sharing DATA segment as USB drive" and "Eject disk to reboot".

My terminal says `Running hello-world on a device` and eventually exits but the device stays the same.

If I inspect the Games directory on the device while it's still mounted, the game isn't there. If I manually eject the device and then look for the game on it, it isn't there either.

**Comment by paulyoung** [comment] 2024-04-25 03:47
Also, using `sudo` doesn't make any difference.

**Comment by paulyoung** [comment] 2024-04-25 14:41
> Or maybe OS didn't mounted your device as drive, so that is bigger problem then `1.`

The device is definitely mounted as a drive; I can explore it and need to eject the disk.

**Comment by paulyoung** [comment] 2024-04-25 14:44
> I'm not sure how works isolation in nix. Is it containerisation?

It’s not, at least not in this case, and I’m using Nix on macOS FWIW.

In this instance I’m using it as a convenient way to set up a developer shell environment, which basically just puts various things on the `PATH`

**Comment by boozook** [comment] 2024-04-25 15:01
Wowowow! For macOs it's more than just strange!

Below I dive you commands that used for linux, not for macOS.

For macOS there is used `diskutil eject /Volumes/<volume-name>`, that is it.

**Comment by boozook** [comment] 2024-04-25 15:19
Oh, I probably know what's happening! That is await time shorter then your OS mounting the device, I suppose.
I have in plan to make wait time configurable.
Well, let's try! I'll make a patch with timeout configuration and we will see.

Anyway, please try commands `pdtool list`, `pdtool mount`, `pdtool mount --wait` (this one is important because there is same timout), `pdtool unmount` and `pdtool unmount --wait`.
_FYI `pdtool` uses same code that used in `cargo-playdate` to interact with device._

**Comment by boozook** [comment] 2024-04-25 18:29
#328 

Configuration env vars: 
- `PD_MOUNT_TIMEOUT`, default `1000` ms
- `PD_UNMOUNT_TIMEOUT`, default `1000` ms.

Values in __milliseconds__.

**Comment by paulyoung** [comment] 2024-04-26 03:08
```
pdtool list
Error:   × missing field `serial_num` at line 31 column 9
```

**Comment by paulyoung** [comment] 2024-04-26 03:09
```
pdtool mount
[ERROR pdtool] Awaiting device timeout `XXXX-XXXXXXX(S)`.
```

This behaved the same as `cargo playdate run --device` but showed the error message at the end.

I just noticed that when both `cargo playdate run --device` and `pdtool mount` are running, the title of my terminal tab switches quickly between `system_profiler` and `pdtool` until the process exits.

![Screen Shot 2024-04-25 at 8 06 52 PM](https://github.com/boozook/playdate/assets/84700/c44c6ec8-0476-4b58-b02d-3ccdc1fc4799)

![Screen Shot 2024-04-25 at 8 06 54 PM](https://github.com/boozook/playdate/assets/84700/e48d37c7-f1a5-44ad-a656-a6bbf1dad507)

Perhaps worth noting that the output above appears to be missing a digit. For example, if my device is `ABC1_D2345678` then the output above is `ABC1-D123456(S)`

**Comment by paulyoung** [comment] 2024-04-26 03:09
```
pdtool mount --wait
[ERROR pdtool] Awaiting device timeout `XXXX-XXXXXXX(S)`.
```

This was the same as without the `--wait` flag.

**Comment by paulyoung** [comment] 2024-04-26 03:10
```
pdtool unmount
Error:   × missing field `serial_num` at line 31 column 9
```

**Comment by paulyoung** [comment] 2024-04-26 03:10
```
pdtool unmount --wait
Error:   × missing field `serial_num` at line 31 column 9
```

**Comment by boozook** [comment] 2024-04-26 11:39
> Perhaps worth noting that the output above appears to be missing a digit. For example, if my device is ABC1_D2345678 then the output above is ABC1-D234567(S)

IMHO, there is no problem.

You can get real serial number from device this ways:
1. Physically look at inner top surface of the hole where crank hiding
2. `pdtool send sn && pdtool read` 

Serial number format if `[A-Z]{3}\d-[A-Z]\d{6}`, so there are just six digits at the end. If you see seven, I suppose that last digit is `1` and it's a number of port (USB telmodem device can have multiple ports). Tell me if I was wrong, it could be interesting and point to fix.

Also, to make sure and rule it out as a suspect, I just add tests for it in #329.

**Comment by boozook** [comment] 2024-04-26 12:24
> ```
> pdtool list
> Error:   × missing field `serial_num` at line 31 column 9
> ```

Okay, now I know that you're on no latest macOS, probably on `12.x.x`, because somewhere between 12 and 14 was "little improvement" in the output of `system_profiler`, so now it always returns SN if possible. Okay, if I right and that is it, I'll fix it.

**Comment by boozook** [comment] 2024-04-26 12:26
@paulyoung, may I ask you to connect your device and execute `system_profiler -json SPUSBDataType` and tell me the output? 🙄

**Comment by paulyoung** [comment] 2024-04-27 00:22
> If you see seven, I suppose that last digit is `1` and it's a number of port (USB telmodem device can have multiple ports)

That appears to be the case, sorry for the confusion.

**Comment by paulyoung** [comment] 2024-04-27 00:24
> Okay, now I know that you're on no latest macOS, probably on `12.x.x`, because somewhere between 12 and 14 was "little improvement" in the output of `system_profiler`, so now it always returns SN if possible. Okay, if I right and that is it, I'll fix it.

I've been putting off upgrading just because I didn't want to deal with any churn that might come with it 😄 

I'm on 12.2.1

**Comment by paulyoung** [comment] 2024-04-27 00:42
I omitted a lot of fields for brevity and changed the names of things between angle brackets for privacy and security. I also redacted the serial number.

```json
{
  "SPUSBDataType" : [
    {
      "_items" : [
        {
          "_items" : [
            {
              "_name" : "USB3.1 Hub             "
            }
          ],
          "_name" : "USB3.0 Hub"
        },
        {
          "_items" : [
            {
              "_name" : "<kvm hub>"
            },
            {
              "_items" : [
                {
                  "_name" : "<keyboard 1>"
                },
                {
                  "_name" : "<keyboard 2>"
                },
                {
                  "_name" : "<trackpad>"
                }
              ],
              "_name" : "USB2.0 Hub             "
            }
          ],
          "_name" : "USB2.0 Hub"
        }
      ],
      "_name" : "USB31Bus"
    },
    {
      "_name" : "USB31Bus"
    },
    {
      "_name" : "USB31Bus"
    },
    {
      "_items" : [
        {
          "_items" : [
            {
              "_name" : "<webcam>"
            }
          ],
          "_name" : "hub_device"
        },
        {
          "_name" : "Playdate",
          "bcd_device" : "2.00",
          "bus_power" : "500",
          "bus_power_used" : "100",
          "device_speed" : "full_speed",
          "extra_current_used" : "0",
          "location_id" : "0x03200000 / 6",
          "manufacturer" : "Panic Inc",
          "product_id" : "0x5740",
          "serial_num" : "XXXX-XXXXXXX",
          "vendor_id" : "0x1331"
        },
        {
          "_items" : [
            {
              "_name" : "USB Controls"
            }
          ],
          "_name" : "hub_device"
        }
      ],
      "_name" : "USB31Bus"
    }
  ]
```

**Comment by paulyoung** [comment] 2024-04-27 00:53
I ran `CARGO_PLAYDATE_LOG=trace cargo playdate run --device` and looked at the code that calls `system_profiler` so have a better understanding of what that's trying to do now.

```
...
[DEBUG playdate_device::mount::methods] retries: 500 * 100ms ≈ 50s.
[TRACE polling] Poller::notify()
[TRACE polling::kqueue] notify: kqueue_fd=10
[TRACE polling::kqueue] new events: kqueue_fd=10, res=1
[TRACE async_io::reactor] process_timers: 0 ready wakers
[TRACE async_io::reactor] react: 0 ready wakers
[TRACE async_io::driver] main_loop: waiting on I/O
[TRACE async_io::reactor] process_timers: 0 ready wakers
[TRACE polling] Poller::wait(_, Some(99.978791ms))
[TRACE polling::kqueue] wait: kqueue_fd=10, timeout=Some(99.978791ms)
[TRACE polling::kqueue] new events: kqueue_fd=10, res=0
[TRACE async_io::reactor] process_timers: 1 ready wakers
[TRACE async_io::reactor] react: 1 ready wakers
[TRACE async_io::driver] main_loop: waiting on I/O
[TRACE async_io::reactor] process_timers: 0 ready wakers
[TRACE polling] Poller::wait(_, None)
[TRACE polling::kqueue] wait: kqueue_fd=10, timeout=None
[TRACE playdate_device::mount::methods] waiting mount point availability: XXXX-XXXXXXX, current: S, try: 1/500
[DEBUG playdate_device::mount::methods] ERROR: missing field `serial_num` at line 31 column 9
[DEBUG playdate_device::mount::methods] mount point still not found, waiting...
...
```

I think `ERROR: missing field `serial_num` at line 31 column 9` must be the issue but it's there in the JSON and appears in the output after `waiting mount point `availability`

**Comment by paulyoung** [comment] 2024-04-27 01:45
I did this locally and got a bit further.

```diff
diff --git a/support/device/src/mount/mac.rs b/support/device/src/mount/mac.rs
index 498e984..b2c5eb9 100644
--- a/support/device/src/mount/mac.rs
+++ b/support/device/src/mount/mac.rs
@@ -80,7 +80,7 @@ pub mod unmount {
 pub struct SpusbInfo<Fut>
        where Fut: Future<Output = Result<PathBuf, Error>> {
        pub name: String,
-       pub serial: String,
+       pub serial: Option<String>,
        pub volume: Fut,
 }
 
@@ -89,7 +89,9 @@ pub struct SpusbInfo<Fut>
 pub async fn volume_for<Info>(dev: Info) -> Result<Volume, Error>
        where Info: AsRef<nusb::DeviceInfo> {
        if let Some(sn) = dev.as_ref().serial_number() {
-               let res = spusb(move |info| info.serial_num == sn).map(|mut iter| iter.next().map(|info| info.volume));
+               let res = spusb(move |info| info.serial_num == Some(sn.to_string())).map(|mut iter| {
+                                                                                           iter.next().map(|info| info.volume)
+                                                                                   });
                match res {
                        Ok(None) => Err(Error::not_found()),
                        Ok(Some(fut)) => Ok(fut),
@@ -118,7 +120,7 @@ pub async fn volumes_for_map<I>(devs: I) -> Result<HashMap<Device, Option<Volume
        for info in spusb(|_| true)? {
                let i = devs.iter()
                            .enumerate()
-                           .find(|(_, (_, sn))| &info.serial == sn)
+                           .find(|(_, (_, sn))| info.serial == Some(sn.to_string()))
                            .map(|(i, _)| i);
 
                if let Some(i) = i {
@@ -149,7 +151,7 @@ pub fn volumes_for<'i, I: 'i>(
        spusb(|_| true).map(move |iter| {
                               iter.filter_map(move |info| {
                                           devs.iter()
-                                              .find(|(_, sn)| info.serial == *sn)
+                                              .find(|(_, sn)| info.serial == Some(sn.to_string()))
                                               .map(|(dev, _)| (info.volume, *dev))
                                   })
                       })
@@ -254,7 +256,7 @@ struct ControllerInfo {
 pub struct DeviceInfo {
        #[serde(rename = "_name")]
        pub name: String,
-       pub serial_num: String,
+       pub serial_num: Option<String>,
        pub vendor_id: String,
 
        #[serde(rename = "Media")]
```

It eventually fails with `[ERROR playdate_device::run] Awaiting XXXX-XXXXXXX(S): filesystem not available at  after 120 retries timeout.`

**Comment by paulyoung** [comment] 2024-04-27 01:47
Before that I see:

```
[TRACE playdate_device::mount::volume] not mounted yet, create resolver fut
[DEBUG playdate_device::mount::methods] XXXX-XXXXXXX mounted, volume found: ''
[DEBUG playdate_device::mount::methods] retries: 120 * 500ms ≈ 60s.
```

**Comment by paulyoung** [comment] 2024-04-27 01:59
(although I would expect not to keep retrying if JSON decoding fails, perhaps that would be worth doing)

**Comment by paulyoung** [comment] 2024-04-27 02:12
I traced the value passed to `Volume::from` here and got a different result this time:

```
[TRACE playdate_device::mount::volume] existing, by name: /Volumes/PLAYDATE
[TRACE playdate_device::mount::volume] *************** "/Volumes/PLAYDATE"
[DEBUG playdate_device::mount::methods] XXXX-XXXXXXX mounted, volume found: '/Volumes/PLAYDATE'
```

https://github.com/boozook/playdate/blob/de8d14cf9b1e689bfed610d9dff60cf0bc452e74/support/device/src/mount/mac.rs#L101

The game installed and ran on my device. I reverted the change and it still works. I'm not sure what happened before that when I got `volume found ''`

**Comment by boozook** [comment] 2024-04-27 12:51
>  I'm not sure what happened before that when I got volume found ''

I know when mount point can be empty.

There is fn `mount_point_for_partition` that used as fallback to get mount-point by disk internal UUID. I case when drive already initialised in the driver and OS initialized auto-mount process (or not yet) it can be just empty!
I've forget about it! Thanks!

How to reproduce it:

```bash
# requires jq
cargo run -p=playdate-tool mount && \
export PD_VOLUME_UUID=$(system_profiler -json SPUSBDataType | jq '.SPUSBDataType.[] | select(._items) | ._items.[].Media.[].volumes.[] | select(._name=="PLAYDATE") | .volume_uuid' -r) && \
diskutil info -plist $PD_VOLUME_UUID
```

There will be
```plist
<key>MountPoint</key>
<string></string>
```

Wait,
And then __after OS finally completely mounted the drive we can repeat it without `pdtool mount` and get following:
```plist
<key>MountPoint</key>
<string>/Volumes/PLAYDATE</string>
```

I hope I fixed it in #330.

**Comment by boozook** [comment] 2024-04-27 13:00
> I did this locally and got a bit further. ([comment](https://github.com/boozook/playdate/issues/326#issuecomment-2080310171))

That's ok, I'm sure, because we are not interested in incomplete reports without serial-number at all. So to drop entire function is easier then continue parse, search item of interest, check is there sn existing, your know.

**Comment by paulyoung** [comment] 2024-04-27 19:38
@boozook I tried #330 and I'm still running into the ``missing field `serial_num` at line 31 column 9`` error.

I think the issue is that serde expects every item in the vec to be `DeviceInfo` and fails because most items don't have a `serial_num` field. If you filtered those out first that would probably fix this.

I also think if we encounter this error it's not worth continuing but right now it retries 500 times.

**Comment by paulyoung** [comment] 2024-04-27 19:43
```
[TRACE playdate_device::mount::methods] waiting mount point availability: XXXX-XXXXXXX, current: S, try: 499/500
[DEBUG playdate_device::mount::methods] ERROR: missing field `serial_num` at line 31 column 9
[DEBUG playdate_device::mount::methods] mount point still not found, waiting...
[ERROR playdate_device::run] Awaiting device timeout `XXXX-XXXXXXX(S)`.
```

**Comment by boozook** [comment] 2024-04-27 22:09
#331. There is fix for devs without serial that can break parsing entire doc.

**Comment by boozook** [comment] 2024-04-29 13:16
I just merged #331 into #328 because 
- I hope that it fixes this issue
- there are important fixes anyway

**Comment by paulyoung** [comment] 2024-05-01 01:06
I tried `main` at 5f03a23ea8904799c7b26d1d371d74443ec38195 and this issue appears to be fixed. Thanks!

**Comment by paulyoung** [comment] 2024-05-01 01:24
Reopening due to https://github.com/boozook/playdate/pull/327#issuecomment-2087818912

> Strange, I'm running into #326 on this branch despite having pulled in the fixes for that issue.

**Comment by boozook** [comment] 2024-05-01 09:22
@paulyoung I've added debug print of response where error caused. Branch: `dev/debug-326` ([link](https://github.com/boozook/playdate/commit/39a9669cc206466b1c40228bb7867311ec79681f)). You can checkout and build, __or__ take [build from CI](https://github.com/boozook/playdate/actions/runs/8907607412#Artifacts) (see "Artifacts" there).

_I'm a little bit out of ideas, I don't really understand why you're getting this error._ 🤷🏻‍♂️

**Comment by paulyoung** [comment] 2024-05-02 01:21
I tried again from `main` and it works as expected. I'll try `dev/debug-326` just to be sure.

**Comment by paulyoung** [comment] 2024-05-02 01:25
Works great here. Not sure what happened. Thanks again.

**Comment by boozook** [comment] 2024-05-02 07:28
@paulyoung 
That is strange. Don’t hesitate to reopen this issue if something happens again. Thank you so much!

**Comment by paulstraw** [comment] 2024-05-09 03:42
I'm also hitting the issue originally described here. My env:

* macOS 14.4.1, Apple Silicon
* `playdate 0.2.0` specified in Cargo.lock
* rustc 1.80.0-nightly (faefc618c 2024-05-07)

**Comment by boozook** [comment] 2024-05-09 07:40
Hey @paulstraw 👋🏻 
Are you using latest `cargo-playdate`?
Could you try `pdtool mount` and `... unmount`, just as experiment?

**Comment by paulyoung** [comment] 2024-05-09 15:00
I'm sure the last issue I posted about here was due to the wrong/old build of `cargo-playdate` hanging around in my Nix dev shell.

It happened again when I was working on the Lua API PR and had pulled in some changes from the main branch. I'm not yet sure why it happens when I do that but I was able to identify it and make sure I was using the correct build.

All of that to say, this issue remains fixed for me at the moment.

**Comment by paulstraw** [comment] 2024-05-10 05:29
Thanks guys, appreciate the prompt and thorough responses.

```
» cargo-playdate --version
cargo 0.4.10
```

When running `pdtool mount --wait`, the connected Playdate enters data disk mode very quickly. My shell sits waiting for a minute or so, eventually timing out with ``[ERROR pdtool] Awaiting device timeout `PDU1-YMYSERIAL(S)`.``. The Playdate is visible in Finder as expected during/after.

**Comment by boozook** [comment] 2024-05-10 11:05
@paulstraw I suppose its about changed format of `system_profiler`.

To get exactly what's wrong I recommend do two steps.

But first of all set `RUST_LOG` and `CARGO_PLAYDATE_LOG` env vars to `"trace`.

Well, first step is to mount device somehow (use `pdutil`, `pdtool` or by hand) and then run following command and show me the output (I need just structure with names of fields and to know that value if empty or not)
```bash
system_profiler -json SPUSBDataType
```

Second is similar, but imitate used fallback method to determine mount-point:
```bash
# requires jq
export PD_VOLUME_UUID=$(system_profiler -json SPUSBDataType | jq '.SPUSBDataType.[] | select(._items) | ._items.[].Media.[].volumes.[] | select(._name=="PLAYDATE") | .volume_uuid' -r) && \
diskutil info -plist $PD_VOLUME_UUID
```

([same as above](https://github.com/boozook/playdate/issues/326#issuecomment-2080585751))

This way we can understand whether the problem is in the output format or not.

**Comment by paulstraw** [comment] 2024-05-11 01:08
<details>
<summary>
<code>» RUST_LOG=trace CARGO_PLAYDATE_LOG=trace system_profiler -json SPUSBDataType</code>
</summary>

A bunch of output removed for brevity/privacy:

```
{
  "SPUSBDataType" : [
    {
      "_items" : [
        {
          "_items" : [
            {
              "_name" : "Playdate",
              "bcd_device" : "2.00",
              "bus_power" : "500",
              "bus_power_used" : "100",
              "device_speed" : "full_speed",
              "extra_current_used" : "0",
              "location_id" : "0x05310000 / 24",
              "manufacturer" : "Panic Inc",
              "Media" : [
                {
                  "_name" : "Playdate",
                  "bsd_name" : "disk24",
                  "Logical Unit" : 0,
                  "partition_map_type" : "master_boot_record_partition_map_type",
                  "removable_media" : "yes",
                  "size" : "3.66 GB",
                  "size_in_bytes" : 3662675968,
                  "smart_status" : "Verified",
                  "USB Interface" : 0,
                  "volumes" : [
                    {
                      "_name" : "PLAYDATE",
                      "bsd_name" : "disk24s1",
                      "file_system" : "MS-DOS FAT32",
                      "free_space" : "2.13 GB",
                      "free_space_in_bytes" : 2133676032,
                      "iocontent" : "Windows_FAT_32",
                      "mount_point" : "/Volumes/PLAYDATE",
                      "size" : "3.66 GB",
                      "size_in_bytes" : 3662675456,
                      "volume_uuid" : "83B4406D-",
                      "writable" : "yes"
                    }
                  ]
                }
              ],
              "product_id" : "0x5741",
              "serial_num" : "PDU1-Y0xxxxx",
              "vendor_id" : "0x1331"
            }
          ],
          "_name" : "4-Port USB 2.0 Hub",
          "bcd_device" : "1.36",
          "bus_power" : "500",
          "bus_power_used" : "0",
          "device_speed" : "high_speed",
          "extra_current_used" : "0",
          "location_id" : "0x05300000 / 3",
          "manufacturer" : "Generic",
          "product_id" : "0x5411",
          "vendor_id" : "0x0bda  (Realtek Semiconductor Corp.)"
        },
      ],
      "_name" : "USB31Bus",
      "host_controller" : "AppleASMediaUSBXHCI",
      "pci_device" : "0x1242 ",
      "pci_revision" : "0x0000 ",
      "pci_vendor" : "0x1b21 "
    },
  ]
}%
```
</details>

Running the second command errors with `jq: error (at <stdin>:313): Cannot iterate over null (null)`. This adjusted command gives the expected UUID: `system_profiler -json SPUSBDataType | jq '.SPUSBDataType[] | ._items[]? | ._items[]?.Media[]?.volumes[]? | select(._name=="PLAYDATE") | .volume_uuid' -r`

**Comment by boozook** [comment] 2024-05-12 19:11
@paulstraw 

> ```text
> {
>   "SPUSBDataType" : [
>     {
>       "_items" : [
>         {
>           "_items" : [
>             {
```

Are you sure that there was two `_items`?

**Comment by paulstraw** [comment] 2024-05-12 19:48
Ah, yes I should have mentioned that. I have a bunch of USB devices/hubs connected to my machine, and previously the Playdate was connected two hubs deep.

Trying the new build, I see the expected behavior and trace/debug output for `pdtool mount --wait` and `pdtool unmount --wait`. I confirmed this new build works with the PD connected directly, 1, 2, and 3 hubs deep. Thanks very much for getting this figured out and fixed so quickly!

**Closed** 2024-05-12 20:07 UTC
Labels: bug, cargo, usb, macOs

**Comment by boozook** [comment] 2024-05-12 20:19
Thank __you__. Done, merged, published.
